### ISSUE TITLE
Adding this in dependencies messed up the original androidx material components

### ISSUE THREAD

**Issue by rexdarel** [algolia/instantsearch-android-mvp#2]
I added this one on my project since I do need to add search posts on my app. Well, it messed up the androidx material components. Buttons are not in the original color, the color of Outlined textinputlayout produces the primary color when focused (which is ugly for me since my primary color is white and accent as purple).. Floating button icon is set to black tint which originally is in color white with purple background color... I do not know how to fix this. It messed up my project.

**Comment by rexdarel** [comment]
I can confirm this that it really messed up the components. I removed it from the dependencies and deleted everything that is related to it and the project went back to normal. I do need search functionality and the androidx. Help

**Comment by q-litzler** [comment]
Hello,

Can you please be more specific as to exactly what dependency you added to your project ?
Ideally, if you can copy paste the gradle lines that you think are responsibles for your issue, would be ideal, and this way I'll be able to better assist you.

Best regards

**Comment by rexdarel** [comment]
Hi @q-litzler this is my dependencies:
    

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0-alpha01'
    implementation 'com.algolia:algoliasearch-android:3.+'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.2'
    implementation 'com.google.firebase:firebase-auth:16.0.3'
    implementation 'com.firebaseui:firebase-ui-firestore:4.2.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
    implementation 'com.jakewharton:butterknife:10.0.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.0.0'
    implementation 'com.github.ragunathjawahar:android-saripaar:android-saripaar-2.0.3'
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
    implementation 'com.github.bumptech.glide:glide:3.7.0'
    implementation 'com.hlab.fabrevealmenu:fab-reveal-menu:1.0.3'
    implementation 'com.mikhaellopez:circularimageview:3.2.0'
    implementation 'com.rengwuxian.materialedittext:library:2.1.4'
}
```

with these dependencies everything works fine. As you can see, I added the algoliasearch for adding objects to the index. But adding the instant search : **implementation 'com.algolia:instantsearch-android:1.+'**  to the dependencies it makes the material components messed up..

**No Instant Search dependency:**
![image](https://user-images.githubusercontent.com/30248326/52485909-dfe74100-2bf4-11e9-8544-c7bd7ca8b760.png)

**With Instant Search dependency:**
![image](https://user-images.githubusercontent.com/30248326/52486445-1a9da900-2bf6-11e9-8e8c-be13b7afd4c1.png)


I found the dependency for androidx here https://discourse.algolia.com/t/getting-java-lang-noclassdeffounderror-for-databindermapperimpl/6507/14
since I was getting the same error "no classdeffounderror:"

**Comment by PLNech** [comment]
Hey @rexdarel, thanks for reporting this and sorry for the slow reply. 
Indeed, until a [Jetifier bug](https://issuetracker.google.com/issues/119776863) is fixed by Google engineers, we had to resort to exposing two lines of artifacts: `instantsearch-android` for AppCompat applications and `instantsearch-androidx` for AndroidX-based apps. You can find relevant instructions in [InstantSearch Android's Readme](https://github.com/algolia/instantsearch-android/blob/master/README.md):

> You can add InstantSearch to your Android application by adding one of the following to your `build.gradle`'s dependencies. **Note that until a [Bug in Jetifier](https://issuetracker.google.com/issues/119776863) is resolved, if you use [AndroidX](https://developer.android.com/jetpack/androidx/) you should target our `instantsearch-androidx` artifacts**.
> ```groovy
> implementation 'com.algolia:instantsearch-android:1.15.2'
> 
> 
> // OR, if your application uses AndroidX
> implementation 'com.algolia:instantsearch-androidx:1.15.2'
> ```

Let us know if you encounter another issue with our libraries and AndroidX. Happy building!

**Comment by rexdarel** [comment]
@PLNech I added this on my dependencies but still gives me the ugly looking ui in material. It still gives the same result from my comment above.

![image](https://user-images.githubusercontent.com/30248326/52949329-ec1e8b80-33b6-11e9-8059-ba4b6e8a4a48.png)
