### ISSUE TITLE
Cannot resolve symbol 'Searcher'

### ISSUE THREAD

**Issue by aamir-github** [algolia/instantsearch-android-mvp#3]
I just downloaded and imported the project, unable to resolve the Searcher class error.

![InstantSearch](https://user-images.githubusercontent.com/11234464/72874568-28b7dd00-3d14-11ea-8110-88cbfa5f3efa.png)

**Comment by spinach** [comment]
Hello,

Can you please use our new example repo here: https://github.com/algolia/instantsearch-android-examples. That repo uses the latest InstantSearch Android version that you can find in our [docs](https://www.algolia.com/doc/guides/building-search-ui/getting-started/android/).
